### ISSUE TITLE
DataTable update fails when table has boolean column

### ISSUE THREAD

**Issue by sandeepc24** [demetrixbio/FSharp.Data.Npgsql#17]
I am using DataTable to update a record and I get error `"Input string was not in a correct format."`. 

I have used this in another place and it works fine there.

Here is the stack trace

```
An unhandled exception has occurred while executing the request.
  System.FormatException: Input string was not in a correct format.
     at System.Data.Common.DbDataAdapter.UpdatedRowStatusErrors(RowUpdatedEventArgs rowUpdatedEvent, BatchCommandInfo[] batchCommands, Int32 commandCount)
     at System.Data.Common.DbDataAdapter.UpdatedRowStatus(RowUpdatedEventArgs rowUpdatedEvent, BatchCommandInfo[] batchCommands, Int32 commandCount)
     at System.Data.Common.DbDataAdapter.Update(DataRow[] dataRows, DataTableMapping tableMapping)
     at System.Data.Common.DbDataAdapter.UpdateFromDataTable(DataTable dataTable, DataTableMapping tableMapping)
     at System.Data.Common.DbDataAdapter.Update(DataTable dataTable)
     at FSharp.Data.Npgsql.Utils.UpdateDataTable(DataTable`1 table, NpgsqlConnection connection, NpgsqlTransaction transaction, Boolean continueUpdateOnError, ConflictOption conflictOption)
```

**Comment by dmitry-a-morozov** [comment]
I'm afraid I need a repro from you. 
It's simply not enough information to work on the issue. 
Maybe you can turn on logging to see what statement sent to database.
http://www.npgsql.org/doc/logging.html

**Comment by sandeepc24** [comment]
I have enable logging but I still can't see where it's failing.

**Comment by sandeepc24** [comment]
It looks like an issue with Npgsql, so I'll close this issue.

**Comment by sandeepc24** [comment]
Here is a test case to reproduce this error

```
-- Table: public.test_addresses

-- DROP TABLE public.test_addresses;

CREATE TABLE public.test_addresses
(
  id uuid NOT NULL,
  city character varying(100),
  country character varying(100),
  street character varying(100),
  suburb character varying(100),
  unit_number character varying(100),
  CONSTRAINT test_addresses_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.test_addresses
  OWNER TO postgres;

```

and here is the code I am using

```
// Learn more about F# at http://fsharp.org

open System
open FSharp.Data.Npgsql

[<Literal>]
let jobSearch = "connection string"

type JobSearch = NpgsqlConnection<jobSearch>

[<EntryPoint>]
let main argv =
    use cmdGetUserAddress =
        JobSearch.CreateCommand<"
            select * from test_addresses
            where id = @AddressId
        ", ResultType.DataTable>(jobSearch)
    let addressTable =
        cmdGetUserAddress.AsyncExecute(
            AddressId = Guid.Parse "a33020a4-8aa9-4e2b-891a-4f4ee91ee967") 
        |> Async.RunSynchronously

    if addressTable.Rows.Count = 0 then
        failwithf "Record not found"
    else
        addressTable.Rows.[0].unit_number <- (Some "abc")
        addressTable.Update(jobSearch) |> ignore

    0 // return an integer exit code
```

**Comment by sandeepc24** [comment]
I am not sure what is really going on but DataTable for updating data is just not working for me.

I tried using it another place and I get following error

```
"Dynamic SQL generation for the DeleteCommand is not supported against a SelectCommand that does not return any key column information."
```

I am not deleting any record here just getting a record using select and updating some columns and applying update.

**Comment by dmitry-a-morozov** [comment]
The error message is confusing and I will try to improve it.
But basically it means that you try to Insert/Update/Delete record in table that doesn't have a primary key.
Make sure you have one defined.

**Comment by dmitry-a-morozov** [comment]
I also tried to run your example for `test_addresses` table update - works just fine on my machine.
Do you still have the issue?

**Comment by sandeepc24** [comment]
Thanks for testing with `test_addresses`. I am still having same issue with it. Here is a screenshot of the nugets in the test project I have

![image](https://user-images.githubusercontent.com/4897654/38177734-0b4e9d52-365a-11e8-8a5d-65928ab5fa5a.png)

Here is the screenshot of the test record
![image](https://user-images.githubusercontent.com/4897654/38177807-37d9b078-365a-11e8-9604-4714f77db6d1.png)

**Comment by sandeepc24** [comment]
Here is the dotnet version I have on my machine
![image](https://user-images.githubusercontent.com/4897654/38177817-77013528-365a-11e8-978d-b47120467ebf.png)

**Comment by dmitry-a-morozov** [comment]
I see. You run on Windows?
What's PostgreSQL version do you use?

**Comment by sandeepc24** [comment]
It is 9.6.

**Comment by dmitry-a-morozov** [comment]
I have same configuration. Still cannot repro.
Can you send me sql statement captured by log?

**Comment by sandeepc24** [comment]
I can't see any sql as the crash happens before sql is generated.

**Comment by dmitry-a-morozov** [comment]
Can you instead of 
```fsharp 
    let addressTable =
        cmdGetUserAddress.AsyncExecute(
            AddressId = Guid.Parse "a33020a4-8aa9-4e2b-891a-4f4ee91ee967") 
        |> Async.RunSynchronously
```
try 
```fsharp 
    let addressTable = cmdGetUserAddress.Execute(AddressId = Guid.Parse "a33020a4-8aa9-4e2b-891a-4f4ee91ee967") 
```
and see if it works.

**Comment by sandeepc24** [comment]
I tried using `Execute` but it also fails with same error.

**Comment by dmitry-a-morozov** [comment]
Can you modify your snippet like
```fsharp
//...
    if addressTable.Rows.Count = 0 then
        failwithf "Record not found"
    else
        printfn "Columns: %A" [ for c in addressTable.Columns -> c.ColumnName, c.DataType ] 
        printfn "Values before modification: %A" addressTable.Rows.[0].ItemArray
        addressTable.Rows.[0].unit_number <- (Some "abc")
        printfn "Values before Update: %A" addressTable.Rows.[0].ItemArray
        addressTable.Update(jobSearch) |> ignore    
        printfn "Values after Update: %A" addressTable.Rows.[0].ItemArray
//...
```
And send me an output.
Thanks.

**Comment by sandeepc24** [comment]
Here is the output

```
Columns: [("id", System.Guid); ("city", System.String); ("country", System.String);
 ("street", System.String); ("suburb", System.String);
 ("unit_number", System.String)]
Values before modification: [|a33020a4-8aa9-4e2b-891a-4f4ee91ee967; "Auckland"; "NZ"; "Albany Street";
  "Albany"; "5"|]
Values before Update: [|a33020a4-8aa9-4e2b-891a-4f4ee91ee967; "Auckland"; "NZ"; "Albany Street";
  "Albany"; "abc"|]

Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Data.Common.DbDataAdapter.UpdatedRowStatusErrors(RowUpdatedEventArgs rowUpdatedEvent, BatchCommandInfo[] batchCommands, Int32 commandCount)
   at System.Data.Common.DbDataAdapter.UpdatedRowStatus(RowUpdatedEventArgs rowUpdatedEvent, BatchCommandInfo[] batchCommands, Int32 commandCount)
   at System.Data.Common.DbDataAdapter.Update(DataRow[] dataRows, DataTableMapping tableMapping)
   at System.Data.Common.DbDataAdapter.UpdateFromDataTable(DataTable dataTable, DataTableMapping tableMapping)
   at System.Data.Common.DbDataAdapter.Update(DataTable dataTable)
   at FSharp.Data.Npgsql.Utils.UpdateDataTable(DataTable`1 table, NpgsqlConnection connection, NpgsqlTransaction transaction, Boolean continueUpdateOnError, ConflictOption conflictOption)
   at Program.main(String[] argv) in C:\Users\sandeep\source\repos\JSTypeProvider\JSTypeProvider\Program.fs:line 29
Press any key to continue . . .
```

**Comment by daz10000** [comment]
I would suspect the guid type.  If you replace that column with a simple string does it work?

**Comment by dmitry-a-morozov** [comment]
It didn't give me much clue either :(
Can you try to run direct ADO.NET code without type provider to see if it works?

```fsharp
    use conn = new Npgsql.NpgsqlConnection(jobSearch)
    conn.Open()
    let addressId = Guid.Parse "a33020a4-8aa9-4e2b-891a-4f4ee91ee967"
    use cmd = new Npgsql.NpgsqlCommand("select * from test_addresses where id = @AddressId", conn)
    cmd.Parameters.AddWithValue("AddressId", addressId) |> ignore
    let addressTable = new System.Data.DataTable()
    do
        use cursor = cmd.ExecuteReader()
        addressTable.Load(cursor)

    if addressTable.Rows.Count = 0 then
        let r = addressTable.NewRow()
        r.["id"] <- addressId
        r.["city"] <- "Auckland"
        r.["country"] <- "NZ"
        r.["street"] <- "Albany Street"
        r.["suburb"] <- "Albany"
        r.["unit_number"] <- "5"
        addressTable.Rows.Add r
    else
        addressTable.Rows.[0].["unit_number"] <- "abc"

    use dataAdapter = new NpgsqlDataAdapter(cmd)
    use builder = new NpgsqlCommandBuilder(dataAdapter)
    let recordsAffected = dataAdapter.Update(addressTable) 
    assert(recordsAffected = 1)
```

**Comment by sandeepc24** [comment]
I tried ado and I get following error

![image](https://user-images.githubusercontent.com/4897654/38409372-4d5a28d2-39d5-11e8-9845-c9d3e5b01adf.png)

**Comment by sandeepc24** [comment]
That works fine

**Comment by sandeepc24** [comment]
I just checked out the source code and built it and referenced the dlls generated from it and tested with the code I submitted originally and it worked fine. It looks like the dlls in nuget might be different to what the builds have generated.

**Comment by dmitry-a-morozov** [comment]
Yes. The latest code in master is slightly diff from the latest nuget package. 
I release a new version 
https://www.nuget.org/packages/FSharp.Data.Npgsql/0.1.32-beta
Check it out and let me know if it works for you.

**Comment by sandeepc24** [comment]
I just tested with the latest version and it is now working fine.

**Comment by dmitry-a-morozov** [comment]
Awesome ! Thanks for your patience ! 
No, I don't have gitter/slack channel. 
I'll think about having one. Thanks for suggestion.
